;;; ar-bibtex.el --- -*- lexical-binding: t; -*-

;;; Code:

(defun ar/bibtex-generate-autokey ()
  "Generate a citation key in year-name-title order.
Uses the same components as `bibtex-generate-autokey' but combines
them as (year name title) rather than the default (name year title)."
  (interactive)
  (let* ((names (bibtex-autokey-get-names))
         (year  (bibtex-autokey-get-year))
         (title (bibtex-autokey-get-title)))
    (concat year names title)))

(defun ar/insert-bibtex-autokey ()
  "Insert autogenerated citation key for BibTeX entry at point."
  (interactive)
  (insert (ar/bibtex-generate-autokey)))

(defun ar/bibtex-mode-h ()
  (require 's)  ;; needed for s-upper-camel-case in autokey generation
  (display-line-numbers-mode)
  (eglot-ensure))

(use-package bibtex
  :ensure nil  ;; built-in
  :hook (bibtex-mode . ar/bibtex-mode-h)
  :init
  (setq bibtex-dialect 'biblatex)
  (setq bibtex-align-at-equal-sign t)
  (setq bibtex-text-indentation 20)
  (add-to-list 'auto-mode-alist '("\\.bibtex\\'" . bibtex-mode))
  ;; Auto-key generation: year-name-title order (differs from bibtex default).
  (setq bibtex-autokey-year-length 4)
  (setq bibtex-autokey-names 1)
  (setq bibtex-autokey-titlewords 3)
  (setq bibtex-autokey-titlewords-stretch 0)
  (setq bibtex-autokey-titleword-length nil)
  (setq bibtex-autokey-titleword-ignore
        '("A" "a" "An" "an" "The" "the"
          "Above" "above" "About" "about" "Across" "across"
          "Against" "against" "Along" "along" "Among" "among"
          "Around" "around" "At" "at" "Before" "before"
          "Behind" "behind" "Below" "below" "Beneath" "beneath"
          "Beside" "beside" "Between" "between" "Beyond" "beyond"
          "By" "by" "Down" "down" "During" "during"
          "Except" "except" "For" "for" "From" "from"
          "In" "in" "Inside" "inside" "Into" "into"
          "Is" "is" "It" "it" "Its" "its"
          "Like" "like" "Near" "near" "Of" "of"
          "Off" "off" "On" "on" "Onto" "onto"
          "Since" "since" "To" "to" "Toward" "toward"
          "Through" "through" "Under" "under" "Until" "until"
          "Up" "up" "Upon" "upon" "With" "with"
          "Within" "within" "Without" "without"
          "And" "and" "But" "but" "Nor" "nor"
          "Or" "or" "So" "so" "Yet" "yet"))
  ;; Requires s.el for CamelCase title-word conversion.
  (setq bibtex-autokey-titleword-case-convert-function #'s-upper-camel-case)
  (setq bibtex-autokey-titleword-separator "")
  ;; Register texlab for bibtex-mode LSP support.
  (with-eval-after-load 'eglot
    (add-to-list 'eglot-server-programs
                 '(bibtex-mode . ("texlab"))))
  :config
  (ar/localleader bibtex-mode-map
    ("k" #'ar/insert-bibtex-autokey)))

(provide 'ar-bibtex)
;;; ar-bibtex.el ends here
